
export const image = {
    render: require('./brand/8x render.png'),
    cup: require('./brand/cupimage.png'),
    blue: require('./brand/image 1.jpg'),
    white: require('./brand/image 2.jpg'),
    parking: require('./brand/parking.png'),
    QuantaGataLogo: require('./brand/QuantaGateLogo.jpg'),
    QuantaLogo: require('./brand/QuantaLogo.jpg'),
    image1: require('./brand/main image.png'),
    QrcodeMachine: require('./brand/QrcodeMachine.png'),
    Feature: require('./brand/feature.png'),
    Security: require('./brand/security.png'),
    Benefits: require('./brand/benefits.png'),
    EaseOfUse: require('./brand/Ease of use.png'),
    Rev: require('./brand/revolution image.png'),
    TMS_Logo: require('./brand/TMS_Logo.png'),
    TMS_Img1: require('./brand/TMS_Img1.png'),
    TMS_Img2: require('./brand/TMS_Img2.png'),
    TMS_Img3: require('./brand/TMS_Img3.png'),
    TMS_Img4: require('./brand/TMS_Img4.png'),
    TMS_Img5: require('./brand/TMS_Img5.png'),
    TMS_Img6: require('./brand/TMS_Img6.png'),
    TMS_Img7: require('./brand/TMS_Img7.png'),
    TMS_Img8: require('./brand/TMS_Img8.png'),
    TMS_Img9: require('./brand/TMS_Img9.png'),
    Login_Image: require('./brand/P007_1-2.png'),

    RED_DOT: require('./theme/full-stop.png'),
    LOGIN_SIDE_IMAGE: require('./brand/P007_1-2.png'),
    AuthenticationImage: require('./theme/authenticationModule.jpg'),
    DashboardModule: require('./theme/dashboardModule.jpg'),
    MockEazy1: require('./theme/MockEazy1.jpg'),
    MockEazy2: require('./theme/MockEazy2.jpg'),

    Register: require('./theme/Register.jpg'),
    Tab1Image: require('./theme/Tab1Image.jpg'),
    Tab2Image: require('./theme/Tab2Image.jpg'),
    Tab3Image: require('./theme/Tab3Image.jpg'),
    Tab4Image: require('./theme/Tab4Image.jpg'),
    Tab5Image: require('./theme/Tab5Image.jpg'),
    Tab6Image: require('./theme/Tab6Image.jpg'),
    InterviewReady: require('./theme/interviewReady.jpg'),
    FormJd: require('./theme/formjd.jpg'),
    LoginLanding: require('./theme/LoginS.jpg'),
    trait: require('./theme/trait.jpg'),
    Communication: require('./theme/communication.jpg'),
    Introduction: require('./theme/IntroductionImage.jpg'),
    DontWorry: require('./theme/dontWorryImage.jpg'),
    AccessReport: require('./theme/report.jpg'),
    BasicReport: require('./theme/basicReport.jpg'),
    SkillMatrix: require('./theme/skillMatrixReport.jpg'),
    CommunicationReport: require('./theme/communicationReport.jpg'),
    TraitReport: require('./theme/TraitReport.jpg'),
    Guideline: require('./theme/guideline.jpg'),
    IntrvuSpace: require('./theme/intrvuSpace.jpg'),
    CreateIntrvu: require('./theme/createIntrvu.png'),
    AccessReportsAndInsights: require('./theme/AccessReportsAndInsights.png'),
    ScheduleAndNotification: require('./theme/ScheduleAndNotification.png'),
    CandidatesAttendInterview: require('./theme/candidatesAttendsInterview.png'),
    CreateJdAddCandidates: require('./theme/createJdAddCandidates.png'),
    AutoApproval: require('./theme/autoApproval.png'),
    InsightsAndReports: require('./theme/InsightsAndReports.png'),
    StreamlinedInterviewAndInsights: require('./theme/StreamlinedInterviewAndInsights.png'),
    passportImage: require('./theme/passportImage.jpg'),
    noVideo: require('./theme/noVideo.png'),
    StreamlinedAutomatedInterview: require('./theme/StreamlinedAutomatedInterview.png'),
    intrvuSpaceIv:require('./theme/intrvuSpaceIv.png')

}