export * from './CallScreen'
export * from './Sectors'
export * from './Profile'
export * from './Header'
export * from './GenerateModal'
export * from './FromJD'
export * from './FromCollection'
export * from './FromSkills'
export * from './LandingNavBar'
export * from './LandingHeader'
export * from './From'
export * from './Data'
export * from './Features'
export * from './Pricing'
export * from './ContactUs'
export * from './Footer'
export * from './Guidelines'
export * from './CallHeader'
export * from './UploadJdCard'
export * from './Tab1'
export * from './Tab2'
export * from './Tab3'
export * from './Tab4'
export * from './Tab5'
export * from './Tab6'
export * from './Reports'
export * from './AuthenticationAndDashboardModule'
export * from './HowItWorks'
export * from './Introduction'





