export * from './AnalyzingAnimation'
export * from './LoginSideContent'
export * from './LoginWithOtp'
export * from './PreparingYourInterview'
export * from './Department'
export * from './Designations'
// export * from './AddTeamMate'
export * from './EmployeeDesignation'
export * from './ManageTeamMate'
export * from './Candidates'
export * from './RegisterAdmin'
export * from './RegisterCompany'
