export const GET_START_CHAT = 'GET_START_CHAT'
export const GET_START_CHAT_SUCCESS = 'GET_START_CHAT_SUCCESS'
export const GET_START_CHAT_FAILURE = 'GET_START_CHAT_FAILURE'

// createKnowledgeGroup

export const CREATE_KNOWLEDGE_GROUP = 'CREATE_KNOWLEDGE_GROUP'
export const CREATE_KNOWLEDGE_GROUP_SUCCESS = 'CREATE_KNOWLEDGE_GROUP_SUCCESS'
export const CREATE_KNOWLEDGE_GROUP_FAILURE = 'CREATE_KNOWLEDGE_GROUP_FAILURE'

// createKnowledgeGroupVariant

export const CREATE_KNOWLEDGE_GROUP_VARIANT = 'CREATE_KNOWLEDGE_GROUP_VARIANT'
export const CREATE_KNOWLEDGE_GROUP_VARIANT_SUCCESS = 'CREATE_KNOWLEDGE_GROUP_VARIANT_SUCCESS'
export const CREATE_KNOWLEDGE_GROUP_VARIANT_FAILURE = 'CREATE_KNOWLEDGE_GROUP_VARIANT_FAILURE'


// getKnowledgeGroups

export const GET_KNOWLEDGE_GROUP = 'GET_KNOWLEDGE_GROUP'
export const GET_KNOWLEDGE_GROUP_SUCCESS = 'GET_KNOWLEDGE_GROUP_SUCCESS'
export const GET_KNOWLEDGE_GROUP_FAILURE = 'GET_KNOWLEDGE_GROUP_FAILURE'

// getKnowledgeGroupVariant

export const GET_KNOWLEDGE_GROUP_VARIANT = 'GET_KNOWLEDGE_GROUP_VARIANT'
export const GET_KNOWLEDGE_GROUP_VARIANT_SUCCESS = 'GET_KNOWLEDGE_GROUP_VARIANT_SUCCESS'
export const GET_KNOWLEDGE_GROUP_VARIANT_FAILURE = 'GET_KNOWLEDGE_GROUP_VARIANT_FAILURE'

// Create Sector

export const CREATE_SECTOR = 'CREATE_SECTOR'
export const CREATE_SECTOR_SUCCESS = 'CREATE_SECTOR_SUCCESS'
export const CREATE_SECTOR_FAILURE = 'CREATE_SECTOR_FAILURE'

// setSelectedRole

export const SET_SELECTED_ROLE = 'SET_SELECTED_ROLE'




// GET SECTOR 

export const GET_SECTORS = 'GET_SECTORS'
export const GET_SECTORS_SUCCESS = 'GET_SECTORS_SUCCESS'
export const GET_SECTORS_FAILURE = 'GET_SECTORS_FAILURE'

// CREATE QUESTION FORM

export const CREATE_QUESTION_FORM = 'CREATE_QUESTION_FORM'
export const CREATE_QUESTION_FORM_SUCCESS = 'CREATE_QUESTION_FORM_SUCCESS'
export const CREATE_QUESTION_FORM_FAILURE = 'CREATE_QUESTION_FORM_FAILURE'

/**
 *  set selected client sectors
 */

export const SET_CLIENT_SECTORS = 'SET_CLIENT_SECTORS'


/**
 *  get register data
 */

export const GET_REGISTER_DATA = 'GET_REGISTER_DATA'





/**
 *  create question section
 */


export const CREATE_QUESTION_SECTION = 'CREATE_QUESTION_SECTION'
// get question forms

export const GET_QUESTIONS_FORM = 'GET_QUESTIONS_FORM'
export const GET_QUESTIONS_FORM_SUCCESS = 'GET_QUESTIONS_FORM_SUCCESS'
export const GET_QUESTIONS_FORM_FAILURE = 'GET_QUESTIONS_FORM_FAILURE'



/**
 *  generateForm
 */


export const GENERATE_FORM = 'GENERATE_FORM'


// get question section

export const GET_QUESTION_SECTION = 'GET_QUESTION_SECTION'
export const GET_QUESTION_SECTION_SUCCESS = 'GET_QUESTION_SECTION_SUCCESS'
export const GET_QUESTION_SECTION_FAILURE = 'GET_QUESTION_SECTION_FAILURE'

// selected question form

export const SET_SELECTED_QUESTION_FORM = 'SET_SELECTED_QUESTION_FORM'

// GET_FORM_SECTION_QUESTIONS

export const GET_FORM_SECTION_QUESTIONS = 'GET_FORM_SECTION_QUESTIONS'
export const GET_FORM_SECTION_QUESTIONS_SUCCESS = 'GET_FORM_SECTION_QUESTIONS_SUCCESS'
export const GET_FORM_SECTION_QUESTIONS_FAILURE = 'GET_FORM_SECTION_QUESTIONS_FAILURE'

// get basic report

export const FETCH_BASIC_REPORT = 'FETCH_BASIC_REPORT'
export const FETCH_BASIC_REPORT_SUCCESS = 'FETCH_BASIC_REPORT_SUCCESS'
export const FETCH_BASIC_REPORT_FAILURE = 'FETCH_BASIC_REPORT_FAILURE'

// GET_MY_PAST_INTERVIEWS

export const GET_MY_PAST_INTERVIEWS = 'GET_MY_PAST_INTERVIEWS'
export const GET_MY_PAST_INTERVIEWS_SUCCESS = 'GET_MY_PAST_INTERVIEWS_SUCCESS'
export const GET_MY_PAST_INTERVIEWS_FAILURE = 'GET_MY_PAST_INTERVIEWS_FAILURE'


// Selected Schedule Id

export const SELECTED_SCHEDULE_ID = 'SELECTED_SCHEDULE_ID'

// GENERATE_SECTION_QUESTIONS

export const FETCH_GENERATE_SECTION_QUESTIONS = 'FETCH_GENERATE_SECTION_QUESTIONS'
export const FETCH_GENERATE_SECTION_QUESTIONS_SUCCESS = 'FETCH_GENERATE_SECTION_QUESTIONS_SUCCESS'
export const FETCH_GENERATE_SECTION_QUESTIONS_FAILURE = 'FETCH_GENERATE_SECTION_QUESTIONS_FAILURE'

// GENERATE_FORM_SECTIONS_AND_QUESTIONS

export const FETCH_GENERATE_FORM_SECTIONS_AND_QUESTIONS = 'FETCH_GENERATE_FORM_SECTIONS_AND_QUESTIONS'
export const FETCH_GENERATE_FORM_SECTIONS_AND_QUESTIONS_SUCCESS = 'FETCH_GENERATE_FORM_SECTIONS_AND_QUESTIONS_SUCCESS'
export const FETCH_GENERATE_FORM_SECTIONS_AND_QUESTIONS_FAILURE = 'FETCH_GENERATE_FORM_SECTIONS_AND_QUESTIONS_FAILURE'

// UPDATE_QUESTION_DETAILS

export const FETCH_UPDATE_QUESTION_DETAILS = 'FETCH_UPDATE_QUESTION_DETAILS'
export const FETCH_UPDATE_QUESTION_DETAILS_SUCCESS = 'FETCH_UPDATE_QUESTION_DETAILS_SUCCESS'
export const FETCH_UPDATE_QUESTION_DETAILS_FAILURE = 'FETCH_UPDATE_QUESTION_DETAILS_FAILURE'
// GENERATE_SECTIONS
export const GENERATE_SECTIONS = 'GENERATE_SECTIONS'
export const GENERATE_SECTIONS_SUCCESS = 'GENERATE_SECTIONS_SUCCESS'
export const GENERATE_SECTIONS_FAILURE = 'GENERATE_SECTIONS_FAILURE'

// create schedule 

export const CREATE_SCHEDULE = 'CREATE_SCHEDULE'
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS'
export const CREATE_SCHEDULE_FAILURE = 'CREATE_SCHEDULE_FAILURE'


// full screen view client screen

export const REMOVE_SIDE_NAV = 'REMOVE_SIDE_NAV'

// state to store the previous value

export const BREADCRUMBS = 'BREADCRUMBS'

// clear breadCrumbs

export const CLEAR_BREADCRUMBS = 'CLEAR_BREADCRUMBS'

// screenRecording Permission

export const SCREEN_RECORDING_PERMISSION = 'SCREEN_RECORDING_PERMISSION'


// recordInterviewSession 

export const INTERVIEW_RECORDER_SESSION = 'INTERVIEW_RECORDER_SESSION'
export const INTERVIEW_RECORDER_SESSION_SUCCESS = 'INTERVIEW_RECORDER_SESSION_SUCCESS'
export const INTERVIEW_RECORDER_SESSION_FAILURE = 'INTERVIEW_RECORDER_SESSION_FAILURE'

// recordedVideoSessionDetails

export const RECORDING_VIDEO_SESSION_DETAILS = 'RECORDING_VIDEO_SESSION_DETAILS'
// create jd variant 

export const POST_JD_VARIANT = 'POST_JD_VARIANT'
export const POST_JD_VARIANT_SUCCESS = 'POST_JD_VARIANT_SUCCESS'
export const POST_JD_VARIANT_FAILURE = 'POST_JD_VARIANT_FAILURE'

// CLEAR_LAST_BREADCRUMB

export const CLEAR_LAST_BREADCRUMB = 'CLEAR_LAST_BREADCRUMB'




// het jd GET ITEM LIST 

export const GET_JD_ITEM_LIST = 'GET_JD_ITEM_LIST'
export const GET_JD_ITEM_LIST_SUCCESS = 'GET_JD_ITEM_LIST_SUCCESS'
export const GET_JD_ITEM_LIST_FAILURE = 'GET_JD_ITEM_LIST_FAILURE'

// GET_SCHEDULE_BASIC_INFO

export const GET_SCHEDULE_BASIC_INFO = 'GET_SCHEDULE_BASIC_INFO'
export const GET_SCHEDULE_BASIC_INFO_SUCCESS = 'GET_SCHEDULE_BASIC_INFO_SUCCESS'
export const GET_SCHEDULE_BASIC_INFO_FAILURE = 'GET_SCHEDULE_BASIC_INFO_FAILURE'




// create new jd schedule
export const CREATE_NEW_JD_SCHEDULE = 'CREATE_NEW_JD_SCHEDULE'




// create new jd schedule
export const SET_SELECTED_SECTION = 'SET_SELECTED_SECTION'

// create corporate variant

export const CREATE_CORPORATE_VARIANT = 'CREATE_CORPORATE_VARIANT'
export const CREATE_CORPORATE_VARIANT_SUCCESS = 'CREATE_CORPORATE_VARIANT_SUCCESS'
export const CREATE_CORPORATE_VARIANT_FAILURE = 'CREATE_CORPORATE_VARIANT_FAILURE'

//  GET_KNOWLEDGE_GROUP_VARIANT_DETAILS

export const GET_KNOWLEDGE_GROUP_VARIANT_DETAILS = 'GET_KNOWLEDGE_GROUP_VARIANT_DETAILS'
export const GET_KNOWLEDGE_GROUP_VARIANT_DETAILS_SUCCESS = 'GET_KNOWLEDGE_GROUP_VARIANT_DETAILS_SUCCESS'
export const GET_KNOWLEDGE_GROUP_VARIANT_DETAILS_FAILURE = 'GET_KNOWLEDGE_GROUP_VARIANT_DETAILS_FAILURE'


/**
 * close interviewx
 */

export const CLOSE_INTERVIEW = 'CLOSE_INTERVIEW'
export const CLOSE_INTERVIEW_SUCCESS = 'CLOSE_INTERVIEW_SUCCESS'
export const CLOSE_INTERVIEW_FAILURE = 'CLOSE_INTERVIEW_FAILURE'