export const GET_START_CHAT = 'GET_START_CHAT'
export const GET_START_CHAT_SUCCESS = 'GET_START_CHAT_SUCCESS'
export const GET_START_CHAT_FAILURE = 'GET_START_CHAT_FAILURE'

// createKnowledgeGroup

export const CREATE_KNOWLEDGE_GROUP = 'CREATE_KNOWLEDGE_GROUP'
export const CREATE_KNOWLEDGE_GROUP_SUCCESS = 'CREATE_KNOWLEDGE_GROUP_SUCCESS'
export const CREATE_KNOWLEDGE_GROUP_FAILURE = 'CREATE_KNOWLEDGE_GROUP_FAILURE'

// createKnowledgeGroupVariant

export const CREATE_KNOWLEDGE_GROUP_VARIANT = 'CREATE_KNOWLEDGE_GROUP_VARIANT'
export const CREATE_KNOWLEDGE_GROUP_VARIANT_SUCCESS = 'CREATE_KNOWLEDGE_GROUP_VARIANT_SUCCESS'
export const CREATE_KNOWLEDGE_GROUP_VARIANT_FAILURE = 'CREATE_KNOWLEDGE_GROUP_VARIANT_FAILURE'


// getKnowledgeGroups

export const GET_KNOWLEDGE_GROUP = 'GET_KNOWLEDGE_GROUP'
export const GET_KNOWLEDGE_GROUP_SUCCESS = 'GET_KNOWLEDGE_GROUP_SUCCESS'
export const GET_KNOWLEDGE_GROUP_FAILURE = 'GET_KNOWLEDGE_GROUP_FAILURE'

// getKnowledgeGroupVariant

export const GET_KNOWLEDGE_GROUP_VARIANT = 'GET_KNOWLEDGE_GROUP_VARIANT'
export const GET_KNOWLEDGE_GROUP_VARIANT_SUCCESS = 'GET_KNOWLEDGE_GROUP_VARIANT_SUCCESS'
export const GET_KNOWLEDGE_GROUP_VARIANT_FAILURE = 'GET_KNOWLEDGE_GROUP_VARIANT_FAILURE'

// Create Sector

export const CREATE_SECTOR = 'CREATE_SECTOR'
export const CREATE_SECTOR_SUCCESS = 'CREATE_SECTOR_SUCCESS'
export const CREATE_SECTOR_FAILURE = 'CREATE_SECTOR_FAILURE'

// setSelectedRole

export const SET_SELECTED_ROLE = 'SET_SELECTED_ROLE'




// GET SECTOR 

export const GET_SECTORS = 'GET_SECTORS'
export const GET_SECTORS_SUCCESS = 'GET_SECTORS_SUCCESS'
export const GET_SECTORS_FAILURE = 'GET_SECTORS_FAILURE'

// CREATE QUESTION FORM

export const CREATE_QUESTION_FORM = 'CREATE_QUESTION_FORM'
export const CREATE_QUESTION_FORM_SUCCESS = 'CREATE_QUESTION_FORM_SUCCESS'
export const CREATE_QUESTION_FORM_FAILURE = 'CREATE_QUESTION_FORM_FAILURE'

/**
 *  set selected client sectors
 */

export const SET_CLIENT_SECTORS = 'SET_CLIENT_SECTORS'





/**
 *  create question section
 */


export const CREATE_QUESTION_SECTION = 'CREATE_QUESTION_SECTION'
// get question forms

export const GET_QUESTIONS_FORM = 'GET_QUESTIONS_FORM'
export const GET_QUESTIONS_FORM_SUCCESS = 'GET_QUESTIONS_FORM_SUCCESS'
export const GET_QUESTIONS_FORM_FAILURE = 'GET_QUESTIONS_FORM_FAILURE'



/**
 *  generateForm
 */


export const GENERATE_FORM = 'GENERATE_FORM'


// get question section

export const GET_QUESTION_SECTION = 'GET_QUESTION_SECTION'
export const GET_QUESTION_SECTION_SUCCESS = 'GET_QUESTION_SECTION_SUCCESS'
export const GET_QUESTION_SECTION_FAILURE = 'GET_QUESTION_SECTION_FAILURE'

// selected question form

export const SET_SELECTED_QUESTION_FORM = 'SET_SELECTED_QUESTION_FORM'

// GET_FORM_SECTION_QUESTIONS

export const GET_FORM_SECTION_QUESTIONS = 'GET_FORM_SECTION_QUESTIONS'
export const GET_FORM_SECTION_QUESTIONS_SUCCESS = 'GET_FORM_SECTION_QUESTIONS_SUCCESS'
export const GET_FORM_SECTION_QUESTIONS_FAILURE = 'GET_FORM_SECTION_QUESTIONS_FAILURE'