/**
 * get cpmpanies
 */
export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS'
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE'
/**
 * alter company status
 */

export const ALTER_COMPANY_STATUS = 'ALTER_COMPANY_STATUS'

/**
 * alter company limits
 */

export const ALTER_COMPANY_LIMIT = 'ALTER_COMPANY_LIMIT'

/*
 get recent interviews
 */

export const GET_RECENT_INTERVIEWS = 'GET_RECENT_INTERVIEWS'
export const GET_RECENT_INTERVIEWS_SUCCESS = 'GET_RECENT_INTERVIEWS_SUCCESS'
export const GET_RECENT_INTERVIEWS_FAILURE = 'GET_RECENT_INTERVIEWS_FAILURE'



/**
 * save edited company details
 */

export const SELECTED_COMPANY = 'SELECTED_COMPANY'


/**
 *  get ongoing schedules
 */


export const FETCH_ONGOING_SCHEDULES = "FETCH_ONGOING_SCHEDULES"
export const FETCH_ONGOING_SCHEDULES_SUCCESS = "FETCH_ONGOING_SCHEDULES_SUCCESS"
export const FETCH_ONGOING_SCHEDULES_FAILURE = "FETCH_ONGOING_SCHEDULES_FAILURE"


/**
 * selected  ongoing schedules
 */

export const SET_SELECTED_ONGOING_SCHEDULE = "SET_SELECTED_ONGOING_SCHEDULE"


/* 
view interview 
 */

export const VIEW_COMPANY_INTERVIEW ='VIEW_COMPANY_INTERVIEW'

/* super admin report reGenerate */

export const FETCH_GENERATE_REPORT = "FETCH_GENERATE_REPORT"
export const FETCH_GENERATE_REPORT_SUCCESS = "FETCH_GENERATE_REPORT_SUCCESS"
export const FETCH_GENERATE_REPORT_FAILURE = "FETCH_GENERATE_REPORT_FAILURE"
