

/**
 * get Api actionType
 */

export const GET_CANDIDATES='GET_CANDIDATES'

export const GET_CANDIDATES_SUCCESS='GET_CANDIDATES_SUCCESS'

export const GET_CANDIDATES_FAILURE='GET_CANDIDATES_FAILURE'





/**
 * add Api actionType
 */

export const ADD_CANDIDATES='ADD_CANDIDATES'


/*
 getJdSection
 */

 export const GET_JDSECTION='GET_JDSECTION'

export const GET_JDSECTION_SUCCESS='GET_JDSECTION_SUCCESS'

export const GET_JDSECTION_FAILURE='GET_JDSECTION_FAILURE'
