export const REGISTER_AS_MEMBER = 'REGISTER_AS_MEMBER'
export const REGISTER_AS_MEMBER_SUCCESS = 'REGISTER_AS_MEMBER_SUCCESS'
export const REGISTER_AS_MEMBER_FAILURE = 'REGISTER_AS_MEMBER_FAILURE'

// URL_MEMBER_LOGIN_USING_PASSWORD

export const MEMBER_LOGIN_USING_PASSWORD = 'MEMBER_LOGIN_USING_PASSWORD'
export const MEMBER_LOGIN_USING_PASSWORD_SUCCESS = 'MEMBER_LOGIN_USING_PASSWORD_SUCCESS'
export const MEMBER_LOGIN_USING_PASSWORD_FAILURE = 'MEMBER_LOGIN_USING_PASSWORD_FAILURE'


// GET otp

export const FETCH_OTP = 'FETCH_OTP'
export const FETCH_OTP_SUCCESS = 'FETCH_OTP_SUCCESS'
export const FETCH_OTP_FAILURE = 'FETCH_OTP_FAILURE'