export const REGISTER_AS_MEMBER = 'REGISTER_AS_MEMBER'
export const REGISTER_AS_MEMBER_SUCCESS = 'REGISTER_AS_MEMBER_SUCCESS'
export const REGISTER_AS_MEMBER_FAILURE = 'REGISTER_AS_MEMBER_FAILURE'

// URL_MEMBER_LOGIN_USING_PASSWORD

export const MEMBER_LOGIN_USING_PASSWORD = 'MEMBER_LOGIN_USING_PASSWORD'
export const MEMBER_LOGIN_USING_PASSWORD_SUCCESS = 'MEMBER_LOGIN_USING_PASSWORD_SUCCESS'
export const MEMBER_LOGIN_USING_PASSWORD_FAILURE = 'MEMBER_LOGIN_USING_PASSWORD_FAILURE'


// GET otp

export const FETCH_OTP = 'FETCH_OTP'
export const FETCH_OTP_SUCCESS = 'FETCH_OTP_SUCCESS'
export const FETCH_OTP_FAILURE = 'FETCH_OTP_FAILURE'


// get member using login otp

export const FETCH_MEMBER_USING_LOGIN_OTP = 'FETCH_MEMBER_USING_LOGIN_OTP'
export const FETCH_MEMBER_USING_LOGIN_OTP_SUCCESS = 'FETCH_MEMBER_USING_LOGIN_OTP_SUCCESS'
export const FETCH_MEMBER_USING_LOGIN_OTP_FAILURE = 'FETCH_MEMBER_USING_LOGIN_OTP_FAILURE'

// registerAsCompany

export const REGISTER_AS_COMPANY = 'REGISTER_AS_COMPANY'
export const REGISTER_AS_COMPANY_SUCCESS = 'REGISTER_AS_COMPANY_SUCCESS'
export const REGISTER_AS_COMPANY_FAILURE = 'REGISTER_AS_COMPANY_FAILURE'


//GET_OTP_FOR_EMAIL_VERIFICATION

export const GET_OTP_FOR_EMAIL_VERIFICATION ='GET_OTP_FOR_EMAIL_VERIFICATION'
export const GET_OTP_FOR_EMAIL_VERIFICATION_SUCCESS ='GET_OTP_FOR_EMAIL_VERIFICATION_SUCCESS'
export const GET_OTP_FOR_EMAIL_VERIFICATION_FAILURE ='GET_OTP_FOR_EMAIL_VERIFICATION_FAILURE'


//VERIFY_EMAIL_USING_OTP

export const VERIFY_EMAIL_USING_OTP ='VERIFY_EMAIL_USING_OTP'
export const VERIFY_EMAIL_USING_OTP_SUCCESS ='VERIFY_EMAIL_USING_OTP_SUCCESS'
export const VERIFY_EMAIL_USING_OTP_FAILURE ='VERIFY_EMAIL_USING_OTP_FAILURE'


export const FETCH_EMAIL_VERIFY ='FETCH_EMAIL_VERIFY'
